# Generated by Django 4.1.3 on 2022-11-22 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0005_institutioninfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutioninfo',
            name='homepage_message',
            field=models.TextField(null=True),
        ),
    ]
