# Generated by Django 4.1.3 on 2022-11-25 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0006_alter_institutioninfo_homepage_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutioninfo',
            name='event_name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='institutioninfo',
            name='activation_message',
            field=models.TextField(null=True),
        ),
    ]
