# Generated by Django 4.1.3 on 2022-11-27 02:09

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0007_institutioninfo_event_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutioninfo',
            name='activation_message',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='institutioninfo',
            name='event_name',
            field=models.CharField(default='কুইজ প্রতিযোগিতা', max_length=250),
        ),
        migrations.AlterField(
            model_name='institutioninfo',
            name='homepage_message',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
