# Generated by Django 4.1.3 on 2022-11-27 05:40

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0008_alter_institutioninfo_activation_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
    ]
